docs/about/about.md

@kungfuchicken I have added the new tech leads to the list in alphabetical order.

added new tech leads to about section

---

docs/about/community.md

Added a process describing how community partners can contribute code to our projects, with links to GitHub documentation and Git/GitHub video tutorial.

added details on how community partners can participate

---

.github/PULL_REQUEST_TEMPLATE/new_contributor.md
docs/about/community.md
docs/about/contributors.md

More details on how to volunteer.

Volunteer sign up

---

docs/about/about.md
docs/project_shelter_volunteers/about.md

Updated the About page and team details on the Shelter Volunteers project about page.

Content changes to About page and Shelter Volunteers project

---

src/css/custom.css

Bug fix for the mobile display it will now display 2 tech leads in 1 grid

bug fix for mobile

---

.github/workflows/deploy.yml

tl;dr deployment is broken, and this should fix it.
the repo is failing to deploy a branch merged to main (see https://github.com/oss-slu/oss-slu.github.io/actions/runs/10621021939); the rest of the pipeline worked
more details on the change are explained in https://github.com/actions/checkout/issues/13#issuecomment-2207006934. if this doesn't fix the issue, i'll have to do some more investigation.

updates to the deployment action

---

.github/workflows/deploy.yml

for more details see https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-first-deployment-with-github_token

it's a permission issue;

---

docs/project_pi4micronaut/about.md

Updated the Tech lead details and also the development priorities list.
Issue #93

Pi4Micronaut Portfolio Updated

---

docs/project_mouser/about.md

**Changes Made:**
- Updated developers section to reflect new tech lead
- Updated User Guide section to be more aligned with the project's current version
- Updated Developer Priorities section per client specifications

Updates Mouser About Page

---

docs/project_wheres_religion_mobile/about.md

tech lead's data updated #83 
Description: Made changes in the tech leads information on the project's portfolio page.
what changes were made?
Tech leads information is updated on the project's portfolio page.
Why were changes made?
The changes were made in the tech lead position.
How was it changed?
Made some changes in the about. md file in the project portfolio and added.
Testing Done:

techlead's information updated in portfolio page. 

---

docs/project_dads/about.md

Updated the tech lead details in the project_dads>about.md file

#98 updated the tech lead info

---

docs/project_wheres_religion_desktop/about.md

tech lead's data updated #111
Description: Made changes in the tech leads information on the project's portfolio page.
what changes were made?
Tech leads information is updated on the project's portfolio page.
Why were changes made?
The changes were made in the tech lead position.
How was it changed?
Made some changes in the about. md file in the project portfolio and added.
Testing Done:

update portfolio page

---

docs/project_bubblescan/about.md

Updates on Tech lead and Development Priorities.

Update bubble scan portfolio

---

docs/portfolio.md

renamed sections to highlight our record of accomplishments and readiness for outside partnerships
moved projects into appropriate sections
added some missing descriptions & links
general cleanup;

restructured to highlight our strengths

---

docs/project_shelter_volunteers/about.md

Fixes #124 
Description: This pull request updates the developers information on the About page.
What was changed?
Updated developer information in the About page.
Why was it changed?
By making these changes, the About page's content is kept up-to-date.
How was it changed?
I made the required changes in the about.md file in the information section.

Updated Developers Section

---

docs/project_wheres_religion_mobile/about.md

updated capstone students details on the portfolio page.

---

docs/project_pilot_data_synchronization/about.md

Changes Made:
Updated the developers section with the new development team’s details (capstone students' names and GitHub links).
Updated the Technical Overview and License sections to include additional project information.
Why it was changed:
To ensure accurate and comprehensive project details.
Testing Done:
Verified the content updates by running the portfolio page locally on localhost.

Updated Portfolio pilot data synchronization project

---

docs/project_wheres_religion_desktop/about.md

capstone team member updated #132
Description: Made changes in the capstone team information on the project's portfolio page.
what changes were made?
capstone team information is updated on the project's portfolio page.
Why were changes made?
The changes were made in the current developer position.
How was it changed?
Made some changes in the about. md file in the project portfolio and added.
Testing Done:

update development team in portfolio page

---

docs/project_pi4micronaut/about.md

This pull request updates our portfolio to include information about our team members

Added team members in the portfolio

---

.gitignore
docs/portfolio.md
docs/project_droneworld/about.md

- Updated `.gitignore` to ignore Visual Studio-specific files and folders.
- Corrected the naming of **Drone World** in the portfolio section.
- Updated content on the **Drone World** about page for accuracy.

Updated Drone World Information

---

docs/project_digital_bone_box/about.md

**Changes Made:** 
Updated the Tech lead and current developers names and Profile page information . Added project's repository.
**What was changed:**
Updated the tech lead name to reflect the current tech lead and revised the description to include additional information about the project’s code repository navigation.
**Why was it changed:**
To ensure accurate information about project.
**Testing Done:**

Updated portfolio

---

docs/project_dads/about.md

Added the new Capstone students, labeled the previous Capstone students as alumni, and reordered all entries alphabetically.

DADS - updated in alphabetical order

---

docs/project_meltshiny/about.md
package-lock.json
package.json

Changes Made: Updated the Tech lead and current developers names and Profile page information . Added Additional details about project's functionalities and benefits
What was changed:
Updated the tech lead name to reflect the current tech lead and revised the description to include additional information about the project’s functionalities and benefits.
Why was it changed:
To ensure accurate information about project leadership and provide a clearer, more comprehensive overview of the project's capabilities and advantages.
Testing Done:

updated Tech Lead name,Current developers names,updated the content

---

blog/2024-12-8-code-and-coffee.md
blog/authors.yml

On Dec 8th 2024, @MutyaSowmya123 @yrlmanoharreddy and I attended "Code and Coffee" meetup event. We had a great time networking with people from diverse backgrounds and experiences.

blog post about experience at code and coffee 12/8/24

---

docs/projects/poa_simulation_surgery/about.md
sidebars.js
src/data/people/currentGradTechLeads.json
src/data/projects/Projects.json

- Added Simulation Surgery as a new Project 
- Added Project entry in file `Project.json`
- Added Project Page in file Projects file named as `about.md`
- No Codebase yet (to be added later)
- No Alumni Developers

Simulation Surgery project and portfolio entry

---

src/data/people/currentGradTechLeads.json
src/data/people/prevGradTechLeads.json

mb I should have read some of the other people's pull requests for updates to get this all in one.

Update current and previous tech leads for Where's Religion

---

docs/projects/iris/about.md

Updated the readme.md file in IRIS with new Tech Lead

UPDATING TEAM

---

README.md

This is considered a good practice in open source communities. We should welcome people to not just contribute code, but also be part of the community that can support each other.

README should contain community guidance

---

docs/projects/baio/about.md
docs/projects/health_app/about.md
docs/projects/md/about.md
docs/projects/mechatronics_vr/about.md
docs/projects/mithraditium/about.md
docs/projects/oss_cicd_automation/about.md
docs/projects/oss_cybersecurity/about.md
docs/projects/oss_dev_analytics/about.md
docs/projects/oss_infra_ops/about.md
docs/projects/simulation_surgery/about.md
docs/projects/smartrobot/about.md
sidebars.js
src/components/projects/ProjectsPage.js
src/data/projects/Projects.json

1. alphabetize existing projects
2. added "stable" label to ProjectsPage to indicate products don't have project teams but are still actively maintained by OSS
3. added new projects missing from sidebar and main page navigation
4. added missing new product/team pages:
* TheHealthApp
* MechatronicsVR
* Mithraditium
* OSS CI/CD & Automation
* OSS Cybersecurity
* OSS Dev Analytics
* OSS Infra/Ops
5. Edited a few details (renamed repo to match rebrand, or edited some wording)
* BAIO
* MaterialDereilleur
* Simulation Surgery
* SMARTRobot

add new projects, clean up existing projects
